# Generated by Django 6.0.3 on 2026-03-12 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القسم (مثلاً: جبر)')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الدرس')),
                ('grade', models.CharField(choices=[('1G', 'الأول الإعدادي'), ('2G', 'الثاني الإعدادي'), ('3G', 'الثالث الإعدادي'), ('1S', 'الأول الثانوي'), ('2S', 'الثاني الثانوي'), ('3S', 'الثالث الثانوي')], max_length=2, verbose_name='الصف الدراسي')),
                ('video_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط فيديو اليوتيوب')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='lessons_pdfs/', verbose_name='ملف المذكرة (PDF)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.category', verbose_name='الفرع / القسم')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'الدروس',
            },
        ),
    ]
