# Generated by Django 6.0.3 on 2026-03-12 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الاختبار')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='pages.lesson', verbose_name='الدرس التابع له')),
            ],
            options={
                'verbose_name': 'اختبار',
                'verbose_name_plural': 'الاختبارات',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='نص السؤال')),
                ('option1', models.CharField(max_length=200, verbose_name='الخيار الأول')),
                ('option2', models.CharField(max_length=200, verbose_name='الخيار الثاني')),
                ('option3', models.CharField(max_length=200, verbose_name='الخيار الثالث')),
                ('option4', models.CharField(max_length=200, verbose_name='الخيار الرابع')),
                ('correct_answer', models.IntegerField(choices=[(1, 'الخيار الأول'), (2, 'الخيار الثاني'), (3, 'الخيار الثالث'), (4, 'الخيار الرابع')], verbose_name='الإجابة الصحيحة')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='pages.quiz')),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'الأسئلة',
            },
        ),
    ]
