# Generated by Django 6.0.3 on 2026-03-13 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود التفعيل')),
                ('is_used', models.BooleanField(default=False, verbose_name='هل استُخدم؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.category', verbose_name='القسم المراد تفعيله')),
            ],
            options={
                'verbose_name': 'كود تفعيل',
                'verbose_name_plural': 'أكواد التفعيل',
            },
        ),
    ]
