# Generated by Django 6.0.3 on 2026-03-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_activationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='grade',
            field=models.CharField(choices=[('1G', 'الأول الإعدادي'), ('2G', 'الثاني الإعدادي'), ('3G', 'الثالث الإعدادي'), ('1S', 'الأول الثانوي'), ('2S', 'الثاني الثانوي'), ('3S', 'الثالث الثانوي')], default='1G', max_length=2, verbose_name='الصف الدراسي التابع له'),
        ),
    ]
