# Generated by Django 6.0.3 on 2026-03-17 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_activationcode_options_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activationcode',
            options={'verbose_name': 'كود تفعيل', 'verbose_name_plural': 'أكواد التفعيل'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'تعليق', 'verbose_name_plural': 'التعليقات'},
        ),
    ]
